wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/DFAD/DFAD_video.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1646589285
    t:
      1:
      - 1
      - 5
      - 37
      - 41
      2:
      - 1
      - 5
      - 37
      - 41
      3:
      - 13
      4: 3.7.12
      5: 0.12.11
      8:
      - 5
