wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/DFAD/DFAD_mars_movinet.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1646892073
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      3:
      - 13
      4: 3.7.12
      5: 0.12.11
      8:
      - 5
